In [6]:
import numpy as np
import pandas as pd
import io
#from google.colab 
#import files

In [7]:
#uploaded = files.upload()
df = pd.read_csv(r"C:\Users\Gazal\Documents\matches.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [0]:
df.head(3)

   id  season       city  ...         umpire1    umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar   NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore     S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon  CK Nandan     NaN

[3 rows x 18 columns]

In [10]:
# Q1. Find the total number of matches played till now in IPL
print("Total no of matches played till now in IPL: ",len(df))

Total no of matches played till now in IPL:  636

In [13]:
# Q2. Create a new dataframe from df which will have all the alternate rows and columns from df starting from 0
new_df=df.iloc[::2 ,::2].copy()
new_df

,id,city,team1,toss_winner,result,winner,win_by_wickets,venue,umpire2
0,1,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,normal,Sunrisers Hyderabad,0,"Rajiv Gandhi International Stadium, Uppal",NJ Llong
2,3,Rajkot,Gujarat Lions,Kolkata Knight Riders,normal,Kolkata Knight Riders,10,Saurashtra Cricket Association Stadium,CK Nandan
4,5,Bangalore,Royal Challengers Bangalore,Royal Challengers Bangalore,normal,Royal Challengers Bangalore,0,M Chinnaswamy Stadium,NaN
6,7,Mumbai,Kolkata Knight Riders,Mumbai Indians,normal,Mumbai Indians,4,Wankhede Stadium,CK Nandan
8,9,Pune,Delhi Daredevils,Rising Pune Supergiant,normal,Delhi Daredevils,0,Maharashtra Cricket Association Stadium,S Ravi
...,...,...,...,...,...,...,...,...,...
626,627,Kanpur,Kolkata Knight Riders,Gujarat Lions,normal,Gujarat Lions,6,Green Park,CK Nandan
628,629,Visakhapatnam,Kings XI Punjab,Kings XI Punjab,normal,Rising Pune Supergiants,4,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon
630,631,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,normal,Kolkata Knight Riders,0,Eden Gardens,M Erasmus
632,633,Bangalore,Gujarat Lions,Royal Challengers Bangalore,normal,Royal Challengers Bangalore,4,M Chinnaswamy Stadium,HDPK Dharmasena
634,635,Delhi,Gujarat Lions,Sunrisers Hyderabad,normal,Sunrisers Hyderabad,4,Feroz Shah Kotla,CK Nandan

In [17]:
# Q3. Find the number of matches played in Mumbai in the period of 2013 and 2017
total=len(df[(df["city"]=="Mumbai") & ((df["season"]>=2013)&(df["season"]<=2017))])
print("Total no of matches played in Mumbai in the period of 2013 and 2017: ",total)

Total no of matches played in Mumbai in the period of 2013 and 2017:  38

In [21]:
# Q4. Find the number of matches where the margin of victory was greater than 30
mg=len(df[(df["win_by_runs"]>30)])
print("Total no of matches where the margin of victory was greater than 30: ",mg)

Total no of matches where the margin of victory was greater than 30:  103

In [22]:
# Q5. What percent times KKR decides to bat after winning the toss
a=len(df[(df["toss_winner"]=="Kolkata Knight Riders") & (df["toss_decision"]=="bat")])
b=len(df[df["toss_winner"]=="Kolkata Knight Riders"])
print("KKR chose to bat ",(a/b*100),"% times after winning the toss")

KKR chose to bat  38.46153846153847 % times after winning the toss